### PR TITLE
Write-ChocolateySuccess and Write-ChocolateyFailure are now deprecated.

### PR DESCRIPTION
**Pull request by KakersUK**
Minor changes so I've not tested this code myself.

### CODE REVIEW

**Comment by KakersUK** [comment]
Empty checksums are no longer allowed by default for non-secure sources.

**Comment by genebean** [comment]
Thanks for this! I'll review and test it out tomorrow if all goes well.

**Comment by KakersUK** [comment]
Np. After the second commit I actually tested it myself, didn't run into any issues.

**Comment by paskal** [comment]
@genebean, we're looking forward for your updates in upstream.

**Comment by genebean** [comment]
We are finally moving to Zabbix 3.2 at work which means I have some time to look at this (finally!). I will do my best to get this updated in the next few days and then pulled in upstream.

**Pull request merged**
